import {
  RES_IMAGE_LINK01,
  RES_IMAGE_LINK02,
  RES_IMAGE_LINK03,
  RES_IMAGE_LINK04,
  RES_IMAGE_LINK05,
  RES_IMAGE_LINK06,
  RES_IMAGE_LINK07,
  RES_IMAGE_LINK08,
} from "./constants";

const resData = [
  {
    id: 1,
    resImage: RES_IMAGE_LINK01,
    resName: "The Combo Company",
    cuisine: "Biryani, North Indian, Asian",
    rating: 4.3,
    eta: "ETA : 38 Minutes",
    costForTwo: 500,
  },
  {
    id: 2,
    resImage: RES_IMAGE_LINK02,
    resName: "KFC",
    cuisine: "Fried Chicken, Chicken Lollipop",
    rating: 4.1,
    eta: "ETA : 55 Minutes",
    costForTwo: 300,
  },
  {
    id: 3,
    resImage: RES_IMAGE_LINK03,
    resName: "Burger King",
    cuisine: "Burgers, Wraps, Rice Bowls",
    rating: 3.9,
    eta: "ETA : 25 Minutes",
    costForTwo: 800,
  },
  {
    id: 4,
    resImage: RES_IMAGE_LINK04,
    resName: "Sadak Chaap",
    cuisine: "Chaap, Gravy Paneer, Indian Breads",
    rating: 4.5,
    eta: "ETA : 40 Minutes",
    costForTwo: 200,
  },
  {
    id: 5,
    resImage: RES_IMAGE_LINK05,
    resName: "La Pino'z Pizza",
    cuisine: "Pizza, Italian, Pasta, Fast Food",
    rating: 4.9,
    eta: "ETA : 15 Minutes",
    costForTwo: 900,
  },
  {
    id: 6,
    resImage: RES_IMAGE_LINK06,
    resName: "Jumboking Burgers",
    cuisine: "Burger, Fast Food, Beverages",
    rating: 3.2,
    eta: "ETA : 43 Minutes",
    costForTwo: 400,
  },
  {
    id: 7,
    resImage: RES_IMAGE_LINK07,
    resName: "Cake Centre-The Dessert Maker",
    cuisine: "Bakery, Desserts",
    rating: 4.5,
    eta: "ETA : 30 Minutes",
    costForTwo: 600,
  },
  {
    id: 8,
    resImage: RES_IMAGE_LINK08,
    resName: "Cheelizza - India Ka Pizza",
    cuisine: "Pizza, Pasta, Italian",
    rating: 4.1,
    eta: "ETA : 50 Minutes",
    costForTwo: 750,
  },
];

export default resData;
